# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\testcenter20190116备份（增加qtextedit中进行发送命令）\testcenter20190102备份\testcenter\Testcenter\testcenter_singlethread\subdialog\loganalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_loganalyzer(object):
    def setupUi(self, loganalyzer):
        loganalyzer.setObjectName("loganalyzer")
        loganalyzer.resize(400, 457)
        self.lineEdit_logpath = QtWidgets.QLineEdit(loganalyzer)
        self.lineEdit_logpath.setGeometry(QtCore.QRect(100, 20, 231, 20))
        self.lineEdit_logpath.setText("")
        self.lineEdit_logpath.setObjectName("lineEdit_logpath")
        self.label = QtWidgets.QLabel(loganalyzer)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.label.setObjectName("label")
        self.selectpath = QtWidgets.QPushButton(loganalyzer)
        self.selectpath.setGeometry(QtCore.QRect(330, 20, 51, 20))
        self.selectpath.setObjectName("selectpath")
        self.lineEdit_searchchar = QtWidgets.QLineEdit(loganalyzer)
        self.lineEdit_searchchar.setGeometry(QtCore.QRect(10, 89, 371, 21))
        self.lineEdit_searchchar.setText("")
        self.lineEdit_searchchar.setObjectName("lineEdit_searchchar")
        self.label_3 = QtWidgets.QLabel(loganalyzer)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 341, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(loganalyzer)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 171, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_saveline = QtWidgets.QLineEdit(loganalyzer)
        self.lineEdit_saveline.setGeometry(QtCore.QRect(190, 130, 191, 20))
        self.lineEdit_saveline.setObjectName("lineEdit_saveline")
        self.groupBox = QtWidgets.QGroupBox(loganalyzer)
        self.groupBox.setGeometry(QtCore.QRect(0, 50, 401, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_gen = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_gen.setGeometry(QtCore.QRect(290, 120, 75, 23))
        self.pushButton_gen.setObjectName("pushButton_gen")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 261, 23))
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(loganalyzer)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 240, 401, 251))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 381, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.addColumn = QtWidgets.QPushButton(self.groupBox_2)
        self.addColumn.setGeometry(QtCore.QRect(20, 150, 75, 23))
        self.addColumn.setObjectName("addColumn")
        self.deleteColumn = QtWidgets.QPushButton(self.groupBox_2)
        self.deleteColumn.setGeometry(QtCore.QRect(110, 150, 75, 23))
        self.deleteColumn.setObjectName("deleteColumn")
        self.pushButton_gen_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_gen_2.setGeometry(QtCore.QRect(290, 180, 75, 23))
        self.pushButton_gen_2.setObjectName("pushButton_gen_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 271, 23))
        self.label_2.setObjectName("label_2")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.lineEdit_logpath.raise_()
        self.label.raise_()
        self.selectpath.raise_()
        self.lineEdit_searchchar.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit_saveline.raise_()

        self.retranslateUi(loganalyzer)
        QtCore.QMetaObject.connectSlotsByName(loganalyzer)

    def retranslateUi(self, loganalyzer):
        _translate = QtCore.QCoreApplication.translate
        loganalyzer.setWindowTitle(_translate("loganalyzer", "log分析器"))
        self.label.setText(_translate("loganalyzer", "log文件路径*："))
        self.selectpath.setText(_translate("loganalyzer", "选择"))
        self.label_3.setText(_translate("loganalyzer", "要查找的文字(括号为特殊字符之前需要加反斜杆)*："))
        self.label_4.setText(_translate("loganalyzer", "提取查找到文字的后面第几行："))
        self.lineEdit_saveline.setText(_translate("loganalyzer", "0,1,2"))
        self.groupBox.setTitle(_translate("loganalyzer", "提取并保存为文本："))
        self.pushButton_gen.setText(_translate("loganalyzer", "开始生成"))
        self.label_5.setText(_translate("loganalyzer", "自动生成带日期的文本文件到log文件路径下"))
        self.groupBox_2.setTitle(_translate("loganalyzer", "提取并保存为excel："))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("loganalyzer", "列名"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("loganalyzer", "匹配表达式"))
        self.addColumn.setText(_translate("loganalyzer", "添加列"))
        self.deleteColumn.setText(_translate("loganalyzer", "删除列"))
        self.pushButton_gen_2.setText(_translate("loganalyzer", "开始生成"))
        self.label_2.setText(_translate("loganalyzer", "自动生成带日期的excel文件到log文件路径下"))

